version: '3.3'
services: 
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_moules
      - .:/app
  test:
    # stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_moules
      - .:/app
    command: ["npm", "run", "test"]
    